services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/data/db.sqlite3
    volumes:
      - app_data:/app/data
      - media_data:/app/media
    restart: unless-stopped

  worker:
    build: .
    command: python manage.py process_tasks
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/data/db.sqlite3
    volumes:
      - app_data:/app/data
      - media_data:/app/media
    depends_on:
      - app
    restart: unless-stopped

  caddy:
    build:
       context: .
       dockerfile: Dockerfile.caddy
    ports:
      - "8080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped

volumes:
  app_data:
  media_data:
  caddy_data:
  caddy_config:
